### ISSUE TITLE
Extension to other languages

### ISSUE THREAD

**Issue by mirix** [ad-freiburg/whitespace-correction#2]
Hello,

I have started to test your models and so far they seem to do a pretty good job. Thank you!

Any plans to build models for languages other than English? German and French would be great.

Best regards,

Ed

**Comment by bastiscode** [comment]
Yes, we are currently looking into that. We also want to create some models that do spelling correction at the same time.

Cannot give you an estimate of how long until we are ready to release them though.

**Comment by tiendung** [comment]
I'm interested in using whitespace-correction for Vietnamese. How should I prepare training data?

**Comment by bastiscode** [comment]
In general you only need a large corpus of correctly spelled text in the language you're interested in. For Vietnamese you could for example start with a dump of the Vietnamese Wikipedia. 
The preprocessing pipeline then automatically injects whitespace errors during training.
